name: oopsla-rev
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcxx
  - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - liblapack=3.8.0=10_openblas
  - libopenblas=0.3.6
  - libxgboost=0.82
  - llvm-openmp=8.0.0
  - ncurses=6.1
  - numpy=1.16.4
  - openblas=0.3.6
  - openssl=1.0.2r
  - pip=19.1.1
  - py-xgboost=0.82
  - python=3.6.6
  - readline=7.0
  - setuptools=41.0.1
  - sqlite=3.28.0
  - tk=8.6.8
  - wheel=0.33.4
  - xgboost=0.82
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.1
    - appnope==0.1.0
    - astor==0.8.0
    - astunparse==1.6.2
    - attrs==19.1.0
    - backcall==0.1.0
    - beautifulsoup4==4.7.1
    - bleach==1.5.0
    - bs4==0.0.1
    - cliez==2.1.1
    - comb==0.9.10
    - cycler==0.10.0
    - decorator==4.4.0
    - dill==0.3.0
    - future==0.17.1
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.22.0
    - h5py==2.9.0
    - html5lib==0.9999999
    - ipython==7.6.1
    - ipython-genutils==0.2.0
    - jedi==0.14.1
    - jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.1
    - jupyter-core==4.5.0
    - keras==2.0.9
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - nbformat==4.4.0
    - nltk==3.2.5
    - pandas==0.24.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prompt-toolkit==2.0.9
    - protobuf==3.9.0
    - psutil==5.6.3
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyparsing==2.4.0
    - pyrsistent==0.15.3
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyyaml==5.1.1
    - scikit-learn==0.18
    - scipy==0.19.0
    - seaborn==0.9.0
    - six==1.12.0
    - soupsieve==1.9.2
    - tensorboard==1.14.0
    - tensorflow==1.3.0
    - tensorflow-estimator==1.14.0
    - tensorflow-tensorboard==0.1.8
    - termcolor==1.1.0
    - tqdm==4.32.2
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - werkzeug==0.15.4
    - wrapt==1.11.2
